# Generated by Django 4.2.23 on 2025-07-30 22:30

from django.db import migrations, models
import utils.file_utils


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ["id"]},
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="bio",
            new_name="biography",
        ),
        migrations.RemoveField(
            model_name="link",
            name="order",
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to=utils.file_utils.avatar_upload_to
            ),
        ),
    ]
