# Generated by Django 4.2.23 on 2025-08-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0002_alter_link_options_rename_bio_profile_biography_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="label",
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
