# Generated by Django 4.2.23 on 2025-08-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0003_alter_link_label_alter_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="link",
            name="label",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
