# Generated by Django 4.2.23 on 2025-08-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0004_profile_slug_alter_link_label_alter_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
