# Generated by Django 4.2.23 on 2025-08-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0005_alter_profile_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
