# Generated by Django 4.2.23 on 2025-08-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0006_alter_profile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
